### ISSUE TITLE
PHP7 Support

### ISSUE THREAD

**Issue by mario-deluna** [Ponup/phpsdl#19]
Hello There,

I've seen the [Upgrading to PHP7 71fdfa556](https://github.com/Ponup/phpsdl/commit/71fdfa5562961a6a7627051a146f780cc6405216) commit. But I still was not able to get It running. 

I've tried to build it from source and could resolve the linking issues with sdl but executing the examples don't draw a window but also throw no errors.

Then I've tried the installation with _pecl_ but im getting many errors like:

```
In file included from /private/tmp/pear/install/sdl/php_sdl.c:26:
In file included from /private/tmp/pear/install/sdl/php_sdl.h:140:
/private/tmp/pear/install/sdl/php_sdl_cdrom.h:27:18: error: unknown type name 'zend_rsrc_list_entry'
void _sdl_cdrom (zend_rsrc_list_entry *rsrc TSRMLS_DC);
```

which I guess are because pear uses a older source.

Thank very for all the work you put into this project, I would really love to play around with this. 

Best Regards.

**Comment by sebastianbergmann** [comment]
Yes, PHP 7 support for this extension would be awesome.

**Comment by sebastianbergmann** [comment]
Any update on PHP 7 support? Thanks!

**Comment by mario-deluna** [comment]
@sebastianbergmann If you are building something experimental take a look at:

https://github.com/Ponup/phpopengl

I also created a small extension which lets you create a window and draw on it:

https://github.com/mario-deluna/php-glfw

The main difference is Glut vs Glfw and my aim it to make large parts of the API available at the cost of stability. This is quite the opposite of phpopengl which aims at a small & maintainable codebase.

I’ve started a little component library that might help you getting something on the screen: 
https://github.com/mario-deluna/php-game-framework

**Comment by sebastianbergmann** [comment]
Thanks, @mario-deluna. I was also pointed to https://github.com/krakjoe/ui which I'll have a look at as well.

My requirements are very simple: just give me a window and let me put pixels in a given color. Anything more than that (even primitives such as lines or rectangles etc.) would defeat the purpose of what I want to do.

**Comment by remicollet** [comment]
@sebastianbergmann another tip: https://github.com/Letargie/pggi (quite new project)

**Comment by mario-deluna** [comment]
@sebastianbergmann Well I can provide you with a little piece of example code on how to draw single pixels with glfw if you want . But I guess all of these libraries will be a bit of an overkill to draw single pixels.

**Comment by sebastianbergmann** [comment]
I understand that, I just need to "force myself to ignore" the functionality I do not need, I guess.

And yes, such an example would be much appreciated!

**Comment by santiagolizardo** [comment]
Thanks, @mario-deluna, but there is a much simpler code you can use @sebastianbergmann (tested with PHP7)

```php
// Clear screen
SDL_SetRenderDrawColor($renderer, 0, 0, 0, 0);
SDL_RenderClear($renderer);

// Draw line
SDL_SetRenderDrawColor($renderer, 255, 0, 0, 255);
for($i = 0; $i < WINDOW_WIDTH; ++$i) {
    SDL_RenderDrawPoint($renderer, $i, $i);
}
SDL_RenderPresent($renderer);
``` 

A fully working example can be found [here](https://github.com/Ponup/phpsdl/blob/master/examples/draw-line-pixel-by-pixel.php).

**Comment by mario-deluna** [comment]
@santiagolizardo Absolutely, as I said:

> SDL If I remember right has a function to draw single pixels so I understand why you would prefer it.

My example makes uses Glfw which does not provide any shortcut to draw pixels, because it doesn't make sense to do that in OpenGL in the first place.

But does that mean you are able to run this extension in PHP7?

**Comment by santiagolizardo** [comment]
Ah sorry, I missed that point. It does work with PHP7 (in fact is now a requirement to have PHP7.2+), although I am seeing a segfault just after running any piece of SDL code. I am debugging it now but looks like I would be able to push a new version of this extension this weekend.

**Comment by mario-deluna** [comment]
@santiagolizardo That would be amazing! Thank you for putting work into this. In so many situations SDL is so comfortable to quickly try things out.

**Comment by santiagolizardo** [comment]
7 is the only PHP version supported by this extension at this point. If you find any trouble please report it and I will be delighted to fix it for you.
