### ISSUE TITLE
undefined symbols

### ISSUE THREAD

**Issue by remicollet** [Ponup/phpsdl#22]
During the build:

```
warning: implicit declaration of function 'FREE_ZVAL'; did you mean 'ZVAL_ZVAL'? [-Wimplicit-function-declaration]
warning: implicit declaration of function 'MAKE_STD_ZVAL' [-Wimplicit-function-declaration]
warning: implicit declaration of function 'zend_objects_get_address'; did you mean 'zend_object_release'? [-Wimplicit-function-declaration]
warning: implicit declaration of function 'ALLOC_INIT_ZVAL' [-Wimplicit-function-declaration]
etc

```

Trying to load the extension:
`PHP Warning:  PHP Startup: Unable to load dynamic library 'NTS/modules/sdl.so' (tried: NTS/modules/sdl.so (NTS/modules/sdl.so: undefined symbol: zend_objects_store_add_ref), /opt/remi/php72/root/usr/lib64/php/modules/NTS/modules/sdl.so.so (/opt/remi/php72/root/usr/lib64/php/modules/NTS/modules/sdl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
`

**Comment by santiagolizardo** [comment]
Instead of fixing all these warnings I decided to remove the code knowing that it is not critical to have it and is going to be better to reimplement it using PHP7 APIs rather than upgrading it.
