### ISSUE TITLE
SDL_GetWindowSize and SDL_GetWindowPosition

### ISSUE THREAD

**Issue by b-viguier** [Ponup/phpsdl#24]
Hello,
I didn't achieved to use functions `SDL_GetWindowSize` and `SDL_GetWindowPosition`…
I checked [source code](https://github.com/Ponup/phpsdl/blob/b46362d9bee8972b174caee0cfa3e68ffe00deb3/window.c#L431), but I wasn't able to really understand what goes wrong.

Is it a known issue? Or did I misuse it? 
Thanks for you help 😃 

Here my test script:
```php
<?php

sdl_init(SDL_INIT_VIDEO);
$window = sdl_createwindow(
    'Test',
    SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
    640, 480,
    SDL_WINDOW_SHOWN
);
$renderer = sdl_createrenderer($window, -1, 0);
sdl_setrenderdrawcolor($renderer, 95, 95, 95, 255);

// Make some rendering, to be sure that window is correctly initialized/displayed
$event = new \SDL_Event();
for($i=0; $i<100; ++$i) {
    sdl_pollevent($event);
    sdl_renderclear($renderer);
    sdl_renderpresent($renderer);
    sdl_delay(5);
}

$width = $height = 0;
SDL_GetWindowSize($window, $width, $height);
echo "($width , $height)\n";

$x = $y = 0;
SDL_GetWindowPosition($window, $x, $y);
echo "($x , $y)\n";


sdl_destroyrenderer($renderer);
sdl_destroywindow($window);
sdl_quit();

```

**Comment by santiagolizardo** [comment]
Hi Benoit; There was a bug in the code which was causing input variable references to be ignored. I fixed that now with my latest commit. Hope that helps. Thanks for reporting it.

**Comment by b-viguier** [comment]
Thank you @santiagolizardo !
I definitively have to learn more about Php extension programming, to be able to directly propose this kind of patches… (If you have any resource to share 😄 ).
Have a nice day 🌞
